### ISSUE TITLE
マークダウンでネストして書いたときに、インデントでマークダウンが利用できません。

### ISSUE THREAD

**Issue by nkgrnkgr** [ganta/chrome-extension-marktone#11]
- a
 （ネスト）- aa

のようなとき aa にマークダウンが適応されません。

**Comment by ganta** [comment]
こちら再現できずにおります。

インデントに全角スペースが混入していると再現するのですが、
テキスト中や前後に含まれている文字に特殊なものが存在していたりといったことはないでしょうか？

**Comment by nkgrnkgr** [comment]
今やるとおっしゃる通り全角スペースで再現しますが、半角スペースでは再現しないです！
再現したときは全角スペースだったかもしれません！
ありがとうございます！

**Comment by ganta** [comment]
ご確認ありがとうございます〜
